[package]
name = "rustatusbar"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = { version = "0.30.11", default-features = false }
toml = "0.8.12"
serde = { version = "1.0.197", features = [ "derive" ] }
anyhow = { version = "1.0.86", default-features = false }
